name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker compose up -d --build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          URI: ${{ secrets.URI }}
      - name: Display Logs
        run: python3 -m exendlr robo-scrimblo "ready"
      - name: Cleanup Unused Images
        run: docker image prune -f